/**
 * `mantyl ci` support (trust-and-ci-prd C1): pure summary derivation
 * from a generated passport, plus the GitHub-flavoured outputs the
 * Action consumes. No I/O here; the CLI owns writing to the
 * GITHUB_OUTPUT and GITHUB_STEP_SUMMARY files when those exist.
 */

import type { Passport } from "@mantyl/schema";
import { ExitCode } from "./exit-codes.js";

export interface CiSummary {
  project: string;
  digest: string;
  commit: string | null;
  checksPassed: number;
  checksFailed: number;
  checksSkipped: number;
  checksErrored: number;
  claims: number;
  contradicted: number;
  decisions: number;
  risks: number;
  /**
   * failed: at least one executed check failed or errored.
   * no-sandbox: nothing executed because Docker was unavailable.
   * passed: every executed check passed and at least one ran.
   */
  verdict: "passed" | "failed" | "no-sandbox";
  exitCode: number;
}

export function ciSummary(passport: Passport, sandboxAvailable: boolean): CiSummary {
  const results = passport.verification.results;
  const count = (outcome: string) => results.filter((r) => r.outcome === outcome).length;
  const checksFailed = count("failed");
  const checksErrored = count("error");
  const checksPassed = count("passed");

  const verdict: CiSummary["verdict"] =
    checksFailed + checksErrored > 0 ? "failed" : !sandboxAvailable ? "no-sandbox" : "passed";
  const exitCode =
    verdict === "failed"
      ? ExitCode.VerificationFailed
      : verdict === "no-sandbox"
        ? ExitCode.SandboxUnavailable
        : ExitCode.Ok;

  return {
    project: passport.project.name,
    digest: passport.integrity.passportDigest ?? "",
    commit: passport.run.commit,
    checksPassed,
    checksFailed,
    checksSkipped: count("skipped"),
    checksErrored,
    claims: passport.claims.length,
    contradicted: passport.claims.filter((c) => c.status === "contradicted").length,
    decisions: passport.decisions.length,
    risks: passport.risks.length,
    verdict,
    exitCode,
  };
}

/** key=value lines for the GITHUB_OUTPUT file. */
export function githubOutputLines(summary: CiSummary): string[] {
  return [
    `verdict=${summary.verdict}`,
    `passport-digest=${summary.digest}`,
    `commit=${summary.commit ?? ""}`,
    `checks-passed=${summary.checksPassed}`,
    `checks-failed=${summary.checksFailed}`,
    `checks-skipped=${summary.checksSkipped}`,
    `claims=${summary.claims}`,
    `claims-contradicted=${summary.contradicted}`,
    `risks=${summary.risks}`,
  ];
}

/**
 * Markdown for the GITHUB_STEP_SUMMARY file: the one Checks-area
 * summary per run the ecosystem convention asks for. Prose and a
 * table, no bullets, no em dashes (content rules apply to rendered
 * output wherever it renders).
 */
export function githubStepSummaryMarkdown(summary: CiSummary): string {
  const verdictLine =
    summary.verdict === "passed"
      ? `All ${summary.checksPassed} executed checks passed.`
      : summary.verdict === "failed"
        ? `${summary.checksFailed + summary.checksErrored} of ${
            summary.checksPassed + summary.checksFailed + summary.checksErrored
          } executed checks did not pass.`
        : "No checks executed: the sandbox (Docker) was unavailable on this runner. Evidence stays honest; nothing fake-passes.";
  const lines = [
    `## Mantyl passport · ${summary.project}`,
    "",
    verdictLine,
    "",
    "| Field | Value |",
    "| --- | --- |",
    `| Verdict | ${summary.verdict} |`,
    `| Passport digest | \`${summary.digest || "unstamped"}\` |`,
    `| Commit | \`${summary.commit ?? "not a git repository"}\` |`,
    `| Checks | ${summary.checksPassed} passed · ${summary.checksFailed} failed · ${summary.checksSkipped} skipped |`,
    `| Claims | ${summary.claims} (${summary.contradicted} contradicted) |`,
    `| Decisions | ${summary.decisions} |`,
    `| Risks and unknowns | ${summary.risks} |`,
    "",
    "Generated by mantyl ci · evidence-backed, not a certification.",
    "",
  ];
  return lines.join("\n");
}
