/**
 * @mantyl/renderer-markdown — a PURE consumer of passport.json (spec §4).
 * Deterministic: same passport in, byte-identical markdown out. Never
 * reruns analysis, never alters evidence statuses.
 */

import type { Passport, SourceRef, TruthStatus } from "@mantyl/schema";

const STATUS_LABEL: Record<TruthStatus, string> = {
  "mantyl-verified": "MANTYL VERIFIED",
  "locally-verified": "LOCALLY VERIFIED",
  "repository-confirmed": "REPO",
  "agent-reported": "AGENT",
  "creator-confirmed": "CREATOR",
  inferred: "INFERRED",
  contradicted: "CONTRADICTED",
  unresolved: "UNRESOLVED",
};

function ref(r: SourceRef): string {
  switch (r.kind) {
    case "file":
      return r.lines ? `\`${r.path}:${r.lines[0]}\`` : `\`${r.path}\``;
    case "commit":
      return `commit \`${r.sha.slice(0, 7)}\``;
    case "session":
      return `session \`${r.sessionId}#${r.messageId}\``;
    case "check":
      return `check \`${r.checkId}\``;
    case "creator":
      return `assertion \`${r.assertionId}\``;
  }
}

function refs(list: SourceRef[]): string {
  return list.length === 0 ? "none" : list.map(ref).join(", ");
}

export function renderPassportMarkdown(passport: Passport): string {
  const lines: string[] = [];
  const push = (s = "") => lines.push(s);

  push(`# Project passport · ${passport.project.name}`);
  push();
  push(`> Generated by Mantyl ${passport.run.toolVersion} · ${passport.run.timestamp}`);
  push(`> Commit: ${passport.run.commit ?? "not a git repository"} · Schema ${passport.schemaVersion}`);
  push(`> Passport digest: \`${passport.integrity.passportDigest ?? "unstamped"}\``);
  push();
  push(`Stack: ${passport.project.stack.join(", ")}`);
  push();

  // Section order is a product decision: proof first, reference last.
  // First-user feedback: leading with the env table made the passport read
  // as an env listing; a recipient's first question is "does it work".

  push(`## Verification`);
  push();
  for (const result of passport.verification.results) {
    const exit = result.exitCode !== undefined ? ` (exit ${result.exitCode})` : "";
    push(`- \`${result.checkId}\`: **${result.outcome}**${exit} · ${result.durationMs}ms`);
  }
  if (passport.verification.results.length === 0) {
    push(`- No checks executed. Run \`mantyl verify\` before delivering.`);
  }
  const skippedPlan = passport.verification.plan.filter((c) => !c.selected);
  if (skippedPlan.length > 0) {
    push();
    push(`Not planned: ${skippedPlan.map((c) => `\`${c.id}\` (${c.skipReason ?? c.reason})`).join(", ")}`);
  }
  push();

  if (passport.architecture.narrative) {
    push(`## Architecture (inferred)`);
    push();
    push(passport.architecture.narrative.text);
    push();
  }

  if (passport.architecture.modules.length > 0) {
    push(`## Modules`);
    push();
    for (const m of passport.architecture.modules) {
      push(`- **${m.name}** · \`${m.path}\` [${STATUS_LABEL[m.status]}]`);
    }
    push();
  }

  if (passport.decisions.length > 0) {
    push(`## Decisions`);
    push();
    for (const decision of passport.decisions) {
      const date = decision.date ? ` (${decision.date})` : "";
      push(`- [${STATUS_LABEL[decision.status]}]${date} ${decision.title}`);
      if (decision.rationale !== decision.title) push(`  - ${decision.rationale}`);
      push(`  - evidence: ${refs(decision.refs)}`);
    }
    push();
  }

  push(`## Claims`);
  push();
  for (const claim of passport.claims) {
    push(`- [${STATUS_LABEL[claim.status]}] ${claim.text}`);
    push(`  - evidence: ${refs(claim.refs)}`);
    if (claim.contradictions.length > 0) {
      push(`  - contradicted by: ${refs(claim.contradictions)}`);
    }
  }
  if (passport.claims.length === 0) push(`- No claims recorded.`);
  push();

  push(`## Risks & unknowns`);
  push();
  for (const risk of passport.risks) {
    push(`- [${STATUS_LABEL[risk.status]}] (${risk.severity}) ${risk.text}`);
    if (risk.remediation) push(`  - remediation: ${risk.remediation}`);
  }
  if (passport.risks.length === 0) push(`- None recorded.`);
  push();

  push(`## Incomplete work`);
  push();
  for (const item of passport.incomplete) {
    push(`- ${item.title} · ${refs(item.refs)}`);
  }
  if (passport.incomplete.length === 0) push(`- None recorded.`);
  push();

  push(`## Setup`);
  push();
  for (const step of passport.setup.steps) {
    push(`- \`${step.command}\` [${STATUS_LABEL[step.status]}] · ${refs(step.refs)}`);
  }
  if (passport.setup.steps.length === 0) push(`- No verified setup steps recorded.`);
  push();
  push(`### Environment`);
  push();
  for (const env of passport.setup.env) {
    push(
      `- \`${env.name}\` · ${env.documented ? "documented" : "**NOT documented**"} · ${refs(env.refs)}`
    );
  }
  if (passport.setup.env.length === 0) push(`- No environment variables referenced.`);
  push();

  if (passport.acceptance) {
    const acceptance = passport.acceptance;
    const party = (p: { name: string; organisation?: string | undefined; date: string }) =>
      `${p.name}${p.organisation ? ` (${p.organisation})` : ""} · ${p.date}`;
    push(`## Acceptance`);
    push();
    push(`- Delivered by: ${party(acceptance.deliveredBy)}`);
    if (acceptance.acceptedBy) {
      push(`- Accepted by: ${party(acceptance.acceptedBy)}`);
    } else {
      push(`- Not yet accepted.`);
    }
    if (acceptance.acknowledgedFindings.length > 0) {
      push(
        `- Findings acknowledged at acceptance: ${acceptance.acknowledgedFindings
          .map((id) => `\`${id}\``)
          .join(", ")}`
      );
    }
    push();
  }

  push(`---`);
  push();
  push(`Generated with Mantyl · evidence-backed, not a certification.`);
  push();

  return lines.join("\n");
}
